---

- hosts: web
  become: true
  tasks:
  
  - name: tipo install apache samba
    tags: apache,samba
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - samba
      state: latest
    when: ansible_distribution == "Astra Linux"
  
  - name: tipo copy html
    tags: apache
    copy:
      src: site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db
  become: true
  tasks:

  - name: tipo install db
    tags: mariadb
    apt:
      state: latest
    when: ansible_distribution == "Astra Linux"
