- name: tipo install apache samba
  tags: apache,samba
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - samba
    state: latest

- name: restart apache
  tags: apache
  service:
    name: apache2
    state: restarted

